/*  Written by Andrew Keller
 *
 *  This file is licensed as BSD.  Copyright 2010 Andrew Keller.
 *
 *  JUnit Test Case for LinearArgDesequencer
 */

package com.kfs.bsd.common.util.junit;

import junit.framework.*;
import com.kfs.bsd.common.util.LinearArgDesequencer;

public class TestLinearArgDesequencer extends TestCase {
	
	public void testNoSubclass() {
		
		LinearArgDesequencer args = new LinearArgDesequencer();
		
		assertFalse( "Initializing the LinearArgDesequencer with no arguments should not cause an error.", args.sequenceError() );
		assertEquals( "'No Error' should imply that the error code is zero.", args.sequenceErrorCode(), 0 );
		assertFalse( "LinearArgDesequencer found the help flag when no arguments were supplied.", args.foundHelpFlag() );
		assertEquals( "LinearArgDesequencer found verbosity flag(s) when no arguments were supplied.", args.verbosity(), 0 );
		
		// Human readable tests
		
		System.err.printf( "%nUsage message generated by the LinearArgDesequencer class:%n" );
		for( String line : args.argsUsage() )
			System.err.printf( "%s%n", line );
		
		System.err.printf( "%n%s%n%s%n", "toString generated by the LinearArgDesequencer class:", args );
	}
}
